name: atlas_stack_workspace_project
description: Atlas Stack Workspace Project
publish_to: "none" 

version: 1.0.0

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

    
dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.3.2

lint_staged:
  "lib/**.dart": dart format -l 70 && dart analyze --fatal-infos --fatal-warnings